name: Production

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: checkout repository
        uses: actions/checkout@v1
      - name: install dependencies
        run: npm install
      - name: git config
        run: |
          git config --global user.name 'azukiapesocialclub'
          git config --global user.email 'owenyuwono@gmail.com'
      - name: deploy to production
        run: npm run deploy